// js/language.js

const langData = {
    zh: {
        "banner-title": "全方位金属加工解决方案",
        "banner-desc": "一站式服务，高效便捷",
        "banner-more": "了解更多",
        "stat-sgs": "SGS汽车认证",
        "stat-partner": "战略合作伙伴",
        "stat-capital": "注册资金",
        "stat-area": "总占地面积",
        "stat-building": "建筑面积",
        "factory-title": "精密零配件加工工厂",
        "factory-desc": "先进设备 精湛工艺 专业团队 诚信服务",
        "tab-car": "车载冰箱系列",
        "tab-medical": "医疗领域",
        "tab-equipment": "智能装备领域",
        "tab-energy": "新能源领域",
        "tab-ship": "无人艇领域",
        "tab-airline": "航天领域",
        "car-vertical": "立式冰箱",
        "car-horizontal": "卧式冰箱",
        "medical-robot": "搬运机器人支撑件",
        "medical-cabinet": "机器人空净柜",
        "medical-bracket": "空净机器人支架",
        "equipment-cabinet": "电力五防控制柜",
        "energy-box": "新能源电池盒",
        "energy-roll": "新能源级片卷",
        "ship-box": "户外电力箱",
        "airline-radiator": "航天散热器",
        "ability-title": "加工能力",
        "ability-desc": "十年专注精密零件加工定制服务",
        "machine-turret": "高速数控转塔冲床",
        "machine-turret-desc": "加工材质:软钢、不锈钢、铝",
        "machine-laser": "光纤激光机",
        "machine-laser-desc": "加工材质:钢、不锈钢、铝、铜、紫铜、钛等全部材料",
        "machine-bender": "折弯机",
        "machine-bender-desc": "最大折弯长度:3300mm",
        "factory2-title": "精密零配件加工厂家",
        "factory2-desc": "专业CNC加工定制 精密模具制造 机械零部件加工",
        "advantage-factory": "专业厂家",
        "advantage-equipment": "先进设备",
        "advantage-product": "产品齐全",
        "advantage-service": "服务优势",
        "process-title": "合作流程",
        "process-desc": "专业的技术团队为您提供技术支持和定制方案",
        "process-1": "需求沟通",
        "process-2": "签订协议",
        "process-3": "支付定金",
        "process-4": "设计打样",
        "process-5": "生产加工",
        "process-6": "支付款项",
        "process-7": "准时发货",
        "strength-title": "公司实力",
        "strength-desc": "为了确保满足客户的设计要求，先后引进先进的加工及测试设备",
        "honor-title": "荣誉证书",
        "footer-contact": "联系方式：",
        "footer-tel": "Tel: ***",
        "footer-email": "Email: ***",
        "footer-website": "网址: ***",
        "footer-address": "地址：华实科技",
        "nav-home": "首页",
        "nav-about": "关于我们",
        "nav-products": "产品中心",
        "nav-honors": "荣誉资质",
        "nav-contact": "联系我们",
        "btn-lang": "EN",
        "about-title": "关于华实科技",
        "breadcrumb-home": "首页",
        "breadcrumb-about": "关于华实科技",
        "about-intro-title": "INTRODUCTION",
        "about-company": "珠海华实科技有限公司",
        "about-desc": "珠海华实集团成立于2005年12月,专注于智能钣金19年，为智能制造产业链中最具规模的智能装备企业，专业制造航天航空、汽车、游艇、医疗器械等新能源高端精密装备，为专精特新，高新技术企业，是珠海市智能制造创新基地，珠海市智能制造联合会副会长单位，同时也是珠海市金湾区工商联副主席单位。战略合作伙伴有:冠宇电池、光华科技、创智科技(智能AGV)、宝丰堂(供华为服务器外壳箱体)、珠海精实测控技术股份、中兴智能汽车、太阳鸟游艇等企业。2018年，我们积极响应国家'万企帮万村'的号召，于2018年8月至2021年8月对云南省怒江州贡山县茨开镇茨开村开展了为期3年的一对一帮扶服务并实现脱贫。2018-2020年荣获工商联'热心公益企业'，及'百企帮百村'突出贡献企业称号。",
        "products-title": "产品中心",
        "breadcrumb-home": "首页",
        "breadcrumb-products": "产品中心",
        "category-all": "全部",
        "category-car": "车载冰箱系列",
        "category-medical": "医疗领域",
        "category-equipment": "智能装备领域",
        "category-energy": "新能源领域",
        "category-ship": "无人艇领域",
        "category-airline": "航天领域",
        "car-vertical": "立式冰箱",
        "car-horizontal": "卧式冰箱",
        "medical-robot": "搬运机器人支撑件",
        "medical-cabinet": "机器人空净柜",
        "medical-bracket": "空净机器人支架",
        "equipment-cabinet": "电力五防控制柜",
        "energy-box": "新能源电池盒",
        "energy-roll": "新能源级片卷",
        "ship-box": "户外电力箱",
        "airline-radiator": "航天散热器",
        "pagination-prev": "上一页",
        "pagination-next": "下一页",
        "honors-title": "荣誉资质",
        "breadcrumb-home": "首页",
        "breadcrumb-honors": "荣誉资质",
        "honor1-title": "珠海市智能制造联合会",
        "honor1-year": "副会长单位",
        "honor2-title": "珠海市智能制造联合会",
        "honor2-year": "创新基地",
        "honor3-title": "高新技术企业证书",
        "honor3-year": "证书",
        "honor4-title": "珠海湖南商会",
        "honor4-year": "优秀企业奖",
        "honor5-title": "荣誉证书",
        "honor5-year": "证书",
        "honor6-title": "‘百企帮百村’",
        "honor6-year": "突出贡献企业",
        "honor-title": "荣誉证书",
        "honor7-title": "环保管理体系认证证书",
        "honor7-year": "证书",
        "honor8-title": "管理体系认证",
        "honor8-year": "认证",
        "honor9-title": "质量管理体系认证证书",
        "honor9-year": "证书",
        "contact-title": "联系我们",
        "breadcrumb-home": "首页",
        "breadcrumb-contact": "联系我们",
        "contact-info-title": "联系华实科技",
        "contact-info-desc": "尊敬的访客：",
        "contact-info-welcome": "欢迎进入'联系我们'的页面，感谢您对华实科技金属制品有限公司的关注，我们真诚的期待您的来电！东莞市华实科技金属制品有限公司，用最真诚人心，竭诚以下方式联系我们。",
        "contact-ways-title": "联系方式",
        "contact-phone-title": "电 话：",
        "contact-person-title": "联系人：",
        "contact-email-title": "邮 箱：",
        "contact-fax-title": "传 真：",
        "contact-website-title": "网 址：",
        "contact-address-title": "地 址：",
        "contact-form-title": "在线留言",
        "contact-form-name": "姓名",
        "contact-form-email": "邮箱",
        "contact-form-phone": "电话",
        "contact-form-message": "留言内容",
        "contact-form-submit": "提交",
        "contact-map-title": "公司位置",
    },
    en: {
        "banner-title": "Comprehensive Metal Processing Solutions",
        "banner-desc": "One-stop service, efficient and convenient",
        "banner-more": "Learn More",
        "stat-sgs": "SGS Auto Certification",
        "stat-partner": "Strategic Partners",
        "stat-capital": "Registered Capital",
        "stat-area": "Total Area",
        "stat-building": "Building Area",
        "factory-title": "Precision Parts Processing Factory",
        "factory-desc": "Advanced Equipment · Superb Craftsmanship · Professional Team · Integrity Service",
        "tab-car": "Car Refrigerator Series",
        "tab-medical": "Medical Field",
        "tab-equipment": "Intelligent Equipment",
        "tab-energy": "New Energy",
        "tab-ship": "Unmanned Boat",
        "tab-airline": "Aerospace",
        "car-vertical": "Vertical Refrigerator",
        "car-horizontal": "Horizontal Refrigerator",
        "medical-robot": "Robot Support",
        "medical-cabinet": "Robot Air Purifier Cabinet",
        "medical-bracket": "Air Purifier Robot Bracket",
        "equipment-cabinet": "Power Five-Prevention Cabinet",
        "energy-box": "New Energy Battery Box",
        "energy-roll": "New Energy Sheet Roll",
        "ship-box": "Outdoor Power Box",
        "airline-radiator": "Aerospace Radiator",
        "ability-title": "Processing Capability",
        "ability-desc": "10 Years Focus on Precision Parts Customization",
        "machine-turret": "High-speed CNC Turret Punch",
        "machine-turret-desc": "Materials: Mild Steel, Stainless Steel, Aluminum",
        "machine-laser": "Fiber Laser Machine",
        "machine-laser-desc": "Materials: Steel, Stainless Steel, Aluminum, Copper, Brass, Titanium, etc.",
        "machine-bender": "Bending Machine",
        "machine-bender-desc": "Max Bending Length: 3300mm",
        "factory2-title": "Precision Parts Manufacturer",
        "factory2-desc": "Professional CNC Customization · Precision Mold Manufacturing · Mechanical Parts Processing",
        "advantage-factory": "Professional Manufacturer",
        "advantage-equipment": "Advanced Equipment",
        "advantage-product": "Complete Products",
        "advantage-service": "Service Advantage",
        "process-title": "Cooperation Process",
        "process-desc": "Professional technical team provides support and custom solutions",
        "process-1": "Requirement Communication",
        "process-2": "Sign Agreement",
        "process-3": "Pay Deposit",
        "process-4": "Design & Sample",
        "process-5": "Production",
        "process-6": "Final Payment",
        "process-7": "On-time Delivery",
        "strength-title": "Company Strength",
        "strength-desc": "To meet customer design requirements, we have introduced advanced processing and testing equipment",
        "honor-title": "Honor Certificates",
        "footer-contact": "Contact:",
        "footer-tel": "Tel: ***",
        "footer-email": "Email: ***",
        "footer-website": "Website: ***",
        "footer-address": "Address: Huashi Technology",
        "nav-home": "Home",
        "nav-about": "About Us",
        "nav-products": "Products",
        "nav-honors": "Honors",
        "nav-contact": "Contact Us",
        "btn-lang": "中",
        "about-title": "About Huashi Technology",
        "breadcrumb-home": "Your Location: Home",
        "breadcrumb-about": "About Huashi Technology",
        "about-intro-title": "INTRODUCTION",
        "about-company": "Zhuhai Huashi Technology Co., Ltd.",
        "about-desc": "Zhuhai Huashi Group was established in December 2005, focusing on intelligent sheet metal for 19 years. It is the largest intelligent equipment enterprise in the intelligent manufacturing industry chain, specializing in the manufacturing of high-end precision equipment for aerospace, automotive, yachts, medical devices, and other new energy fields. It is a specialized and innovative high-tech enterprise, an innovation base for intelligent manufacturing in Zhuhai, a vice president unit of the Zhuhai Intelligent Manufacturing Association, and a vice chairman unit of the Jinwan District Federation of Industry and Commerce in Zhuhai. Strategic partners include: Guanyu Battery, Guanghua Technology, Chuangzhi Technology (Intelligent AGV), Baofengtang (Huawei server case supplier), Zhuhai Jingshi Measurement & Control, ZTE Smart Auto, Sunbird Yacht, etc. In 2018, we actively responded to the national call of 'Ten Thousand Enterprises Help Ten Thousand Villages', and from August 2018 to August 2021, we carried out a three-year one-to-one assistance service for Cikai Village, Cikai Town, Gongshan County, Nujiang Prefecture, Yunnan Province, and achieved poverty alleviation. From 2018 to 2020, we were awarded the title of 'Enthusiastic Public Welfare Enterprise' and 'Outstanding Contribution Enterprise for Ten Thousand Enterprises Help Ten Thousand Villages' by the Federation of Industry and Commerce.",
        "products-title": "Products",
        "breadcrumb-home": "Your Location",
        "breadcrumb-products": "Products",
        "category-all": "All",
        "category-car": "Car Refrigerator Series",
        "category-medical": "Medical Field",
        "category-equipment": "Intelligent Equipment",
        "category-energy": "New Energy",
        "category-ship": "Unmanned Boat",
        "category-airline": "Aerospace",
        "car-vertical": "Vertical Refrigerator",
        "car-horizontal": "Horizontal Refrigerator",
        "medical-robot": "Robot Support",
        "medical-cabinet": "Robot Air Purifier Cabinet",
        "medical-bracket": "Air Purifier Robot Bracket",
        "equipment-cabinet": "Power Five-Prevention Cabinet",
        "energy-box": "New Energy Battery Box",
        "energy-roll": "New Energy Sheet Roll",
        "ship-box": "Outdoor Power Box",
        "airline-radiator": "Aerospace Radiator",
        "pagination-prev": "Previous",
        "pagination-next": "Next",
        "honors-title": "Honors",
        "breadcrumb-home": "Your Location",
        "breadcrumb-honors": "Honors",
        "honor1-title": "Zhuhai Intelligent Manufacturing Association",
        "honor1-year": "Vice President Unit",
        "honor2-title": "Zhuhai Intelligent Manufacturing Association",
        "honor2-year": "Innovation Base",
        "honor3-title": "High-tech Enterprise Certificate",
        "honor3-year": "Certificate",
        "honor4-title": "Zhuhai Hunan Chamber of Commerce",
        "honor4-year": "Outstanding Enterprise Award",
        "honor5-title": "Honor Certificate",
        "honor5-year": "Certificate",
        "honor6-title": "'100 Enterprises Help 100 Villages'",
        "honor6-year": "Outstanding Contribution Enterprise",
        "honor-title": "Honor Certificates",
        "honor7-title": "Environmental Management System Certificate",
        "honor7-year": "Certificate",
        "honor8-title": "Management System Certification",
        "honor8-year": "Certification",
        "honor9-title": "Quality Management System Certificate",
        "honor9-year": "Certificate",
        "contact-title": "Contact Us",
        "breadcrumb-home": "Home",
        "breadcrumb-contact": "Contact Us",
        "contact-info-title": "Contact Huashi Technology",
        "contact-info-desc": "Dear Visitor:",
        "contact-info-welcome": "Welcome to the 'Contact Us' page. Thank you for your attention to Huashi Technology Metal Products Co., Ltd. We sincerely look forward to your call! Dongguan Huashi Technology Metal Products Co., Ltd. sincerely welcomes you to contact us in the following ways.",
        "contact-ways-title": "Contact Information",
        "contact-phone-title": "Phone:",
        "contact-person-title": "Contact:",
        "contact-email-title": "Email:",
        "contact-fax-title": "Fax:",
        "contact-website-title": "Website:",
        "contact-address-title": "Address:",
        "contact-form-title": "Online Message",
        "contact-form-name": "Name",
        "contact-form-email": "Email",
        "contact-form-phone": "Phone",
        "contact-form-message": "Message",
        "contact-form-submit": "Submit",
        "contact-map-title": "Company Location",
    }
};

let currentLang = localStorage.getItem('lang') || 'zh';

function setLang(lang) {
    currentLang = lang;
    localStorage.setItem('lang', lang);
    document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.getAttribute('data-lang');
        if (langData[lang][key]) {
            el.innerHTML = langData[lang][key];
        }
    });
    // 按钮文字
    const btn = document.querySelector('[data-lang="btn-lang"]');
    if (btn) btn.innerHTML = langData[lang]['btn-lang'];
    document.body.style.visibility = 'visible';
}

function toggleLanguage() {
    setLang(currentLang === 'zh' ? 'en' : 'zh');
}

// 页面加载时自动切换
document.addEventListener('DOMContentLoaded', function () {
    setLang(currentLang);
});

window.setLang = setLang;